#!/usr/bin/env php
<?php declare(strict_types=1);

// This simple CLI script runs sets needed env
// variables before running php application
// everything what's needed for auto-instrumentation.

$otel_exporters = array(
    "otlp",
    "console",
    "none"
);

function choose_element($elements, $default_index, $command_line): int
{
    $message = "Choose " . $command_line . " (1-" . count($elements) . ") [" . $default_index . "] : ";
    $colorMessage = "\033[31m$message \033[0m";
    $counter = 1;
    foreach ($elements as $element) {
        echo($counter . ") " . $element . "\n");
        ++$counter;
    }
    echo "\n";
    do {
        $element_index = intval(readline($colorMessage));
        if ($element_index == 0) {
            $element_index = $default_index;
            break;
        }
    } while ($element_index < 1 || $element_index > count($elements));
    return $element_index - 1;
}

function choose_otel_traces_exporter($exporters): int
{
    return choose_element($exporters, 1, "trace exporter");
}

function choose_otel_metrics_exporter($exporters): int
{
    return choose_element($exporters, 1, "metrics exporter");
}

function choose_otel_logs_exporter($exporters): int
{
    return choose_element($exporters, 1, "logs exporter");
}

function set_env($otel_exporters)
{
    $message = "set OTEL_PHP_AUTOLOAD_ENABLED=[true]: ";
    $colorMessage = "\033[31m$message \033[0m";
    do {
        $val = readline($colorMessage);
        if ($val == "") {
            $val = "true";
            break;
        }
    } while ($val != "true" && $val != "false");
    $OTEL_PHP_AUTOLOAD_ENABLED = $val;
    putenv('OTEL_PHP_AUTOLOAD_ENABLED=' . $OTEL_PHP_AUTOLOAD_ENABLED);
    echo "\n";

    $exporter_index = choose_otel_traces_exporter($otel_exporters);
    putenv('OTEL_TRACES_EXPORTER=' . $otel_exporters[$exporter_index]);
    echo "\n";

    $exporter_index = choose_otel_metrics_exporter($otel_exporters);
    putenv('OTEL_METRICS_EXPORTER=' . $otel_exporters[$exporter_index]);
    echo "\n";

    $exporter_index = choose_otel_logs_exporter($otel_exporters);
    putenv('OTEL_LOGS_EXPORTER=' . $otel_exporters[$exporter_index]);
    echo "\n";

    $message = "set OTEL_LOG_LEVEL=[info]: ";
    $colorMessage = "\033[31m$message \033[0m";

    $val = readline($colorMessage);
    if ($val == "") {
        $val = "info";
    }
    $OTEL_LOG_LEVEL = $val;
    putenv('OTEL_LOG_LEVEL=' . $OTEL_LOG_LEVEL);
    echo "\n";

    $message = "set OTEL_EXPORTER_OTLP_ENDPOINT=[https://otel.collector.na-01.cloud.solarwinds.com:443]: ";
    $colorMessage = "\033[31m$message \033[0m";

    $val = readline($colorMessage);
    if ($val == "") {
        $val = "https://otel.collector.na-01.cloud.solarwinds.com:443";
    }
    $OTEL_EXPORTER_OTLP_ENDPOINT = $val;
    putenv('OTEL_EXPORTER_OTLP_ENDPOINT=' . $OTEL_EXPORTER_OTLP_ENDPOINT);
    echo "\n";

    $message = "set SW_APM_COLLECTOR=[apm.collector.na-01.cloud.solarwinds.com]: ";
    $colorMessage = "\033[31m$message \033[0m";

    $val = readline($colorMessage);
    if ($val == "") {
        $val = "apm.collector.na-01.cloud.solarwinds.com";
    }
    $SW_APM_COLLECTOR = $val;
    putenv('SW_APM_COLLECTOR=' . $SW_APM_COLLECTOR);
    echo "\n";

    $message = "set SW_APM_SERVICE_KEY=[token:name]: ";
    $colorMessage = "\033[31m$message \033[0m";

    $val = readline($colorMessage);
    if ($val == "") {
        $val = "token:name";
    }
    $SW_APM_SERVICE_KEY = $val;
    putenv('SW_APM_SERVICE_KEY=' . $SW_APM_SERVICE_KEY);
    echo "\n";

    $part = explode(":", $SW_APM_SERVICE_KEY);
    if (count($part) != 2) {
        echo "SW_APM_SERVICE_KEY must be in format 'token:name'!\n";
        exit(1);
    }
    $authorization = 'Authorization=Bearer '.$part[0];
    putenv('OTEL_EXPORTER_OTLP_HEADERS=' . $authorization);
    echo "\n";

    $message = "set OTEL_TRACES_SAMPLER=[solarwinds_http]: ";
    $colorMessage = "\033[31m$message \033[0m";

    $val = readline($colorMessage);
    if ($val == "") {
        $val = "solarwinds_http";
    }
    $OTEL_TRACES_SAMPLER = $val;
    putenv('OTEL_TRACES_SAMPLER=' . $OTEL_TRACES_SAMPLER);
    echo "\n";

    $message = "set OTEL_PROPAGATORS=[baggage,tracecontext,swotracestate,xtraceoptions]: ";
    $colorMessage = "\033[31m$message \033[0m";

    $val = readline($colorMessage);
    if ($val == "") {
        $val = "baggage,tracecontext,swotracestate,xtraceoptions";
    }
    $OTEL_PROPAGATORS = $val;
    putenv('OTEL_PROPAGATORS=' . $OTEL_PROPAGATORS);
    echo "\n";

    $message = "set OTEL_SERVICE_NAME: ";
    $colorMessage = "\033[31m$message \033[0m";

    $val = readline($colorMessage);
    if ($val == "") {
        $val = "auto";
    }
    $OTEL_SERVICE_NAME = $val;
    putenv('OTEL_SERVICE_NAME=' . $OTEL_SERVICE_NAME);
}

set_env($otel_exporters);

$command = "";
for ($i = 1; $i < $argc; $i++) {
    if ($i > 1) {
        $command = $command . " ";
    }
    $command = $command . $argv[$i];
}

if ($command != "") {
    echo $command . "\n";
    exec($command);
}
